# Generated by Django 4.2.7 on 2024-03-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_rubric_alter_bd_options_alter_bd_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bd',
            name='kind',
            field=models.CharField(choices=[(None, 'Выбирете тип публикуемого объявления'), ('Купля-продажа', (('b', 'Куплю'), ('s', 'Продам'))), ('Обмен', (('c', 'Обменяю'),))], default='s', max_length=1),
        ),
    ]
