# Generated by Django 4.2.7 on 2024-03-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_bd_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd',
            name='kind',
            field=models.CharField(choices=[(None, 'Выбирете тип публикуемого объявления'), ('b', 'Куплю'), ('s', 'Продам'), ('c', 'Обменяю'), ('r', 'Rent')], default='s', max_length=1, verbose_name='Вид'),
        ),
    ]
