# Generated by Django 4.2.7 on 2024-03-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_alter_bd_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measuere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.FloatField(choices=[(1.0, 'Метры'), (0.3048, 'Футы'), (0.9144, 'Ярды')])),
            ],
        ),
    ]
